In [55]:
import numpy as np

In [57]:
#1
arr = np.ones((3,3), dtype = bool)
print("arr: \n",arr)

arr: 
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [ ]:
#2
arr_1D = np.array([0,1,2,3,4,5,6,7,8])
arr_2D = np.reshape(arr_1D, (3,3))
print("arr_2D: \n",arr_2D)

arr_2D[:, [0,2]] = arr_2D[:, [2,0]]
print("arr_2D sau khi đổi cột:\n", arr_2D)

arr_2D: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
arr_2D sau khi đổi cột:
 [[2 1 0]
 [5 4 3]
 [8 7 6]]


In [ ]:
#3
arr_2D[[2,1],:] = arr_2D[[1,2],:] 
print("arr_2D sau khi đổi hàng:\n", arr_2D)

arr_2D sau khi đổi hàng:
 [[5 4 3]
 [2 1 0]
 [8 7 6]]


In [ ]:
#4
print("arr_2D sau khi đảo ngược các dòng: \n ",arr_2D[::-1])

arr_2D sau khi đảo ngược các dòng: 
  [[8 7 6]
 [2 1 0]
 [5 4 3]]


In [ ]:
#5
print("arr_2D sau khi đảo ngược các cột: \n ",arr_2D[:, ::-1])

arr_2D sau khi đảo ngược các cột: 
  [[3 4 5]
 [0 1 2]
 [6 7 8]]


In [ ]:
#6
arr_2D_null = np.array([[1, 2, 3], [np.NaN, 5, 6], [7, np.NaN, 9], [4, 5, 6]])
a = np.isnan(arr_2D_null).any()
print("Có giá trị rỗng trong arr_2D_null:", a)

Có giá trị rỗng trong arr_2D_null: True


In [ ]:
#7
arr_2D_null[np.isnan(arr_2D_null)] = 0
print("arr_2D_null sau khi thay thế:\n", arr_2D_null)

arr_2D_null sau khi thay thế:
 [[1. 2. 3.]
 [0. 5. 6.]
 [7. 0. 9.]
 [4. 5. 6.]]
